substitutions:
  fan_low: D5
  fan_high: D6
  compressor: D7
  status_led: D2
  friendly_name: "Aircondition"
  
  internal_switches: "true"

esphome:
  name: ac
  comment: 'Create cold'

esp8266:
  board: d1_mini_pro

# Enable logging
logger:

# Enable Home Assistant API
api:

web_server:
  port: 80

ota:

wifi:
  ssid: !secret iot_ssid
  password: !secret iot_pass
  
  #ssid: "no"
  #password: "noooooooo"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "AC Fallback Hotspot"
    #password: ""
    ap_timeout: 10s

captive_portal:

status_led:
  pin:
    number: ${status_led}
    inverted: true

interval:
  - interval: 1s
    then:
      if:
        condition:
          - switch.is_on: compressor
        then:
          if:
            condition:
              and:
                - switch.is_off: fan_high
                - switch.is_off: fan_low
            then:
              - switch.turn_on: fan_low
              
  - interval: 5s
    then:
      lambda: !lambda |-
          if(id(acthermostat).mode != CLIMATE_MODE_OFF)
          {
            if ( id(acthermostat).current_temperature > ( id(acthermostat).target_temperature + 1 ) )
            {
              id(fan_low).turn_off();
              id(fan_high).turn_on();
            }
            else
            {
              id(fan_high).turn_off();
              id(fan_low).turn_on();
            }
          }
          
  - interval: 36s
    then:
      - lambda: !lambda |-
      
            id(power_watt) = 0.0;
            
            id(power_consumed) += (1.6 * 0.01) / 1000; // 1.6w
            id(power_watt) += 1.6;
      
      
            if(id(fan_low).state)
            {
              id(power_consumed) += (47 * 0.01) / 1000; // 47w
              id(power_watt) += 47;
            }
            
            if(id(fan_high).state)
            {
              id(power_consumed) += (53 * 0.01) / 1000; // 53w
              id(power_watt) += 53;
            }
            
            if(id(compressor).state)
            {
              id(power_consumed) += (670 * 0.01) / 1000; // 670w
              id(power_watt) += 670;
            }

            id(total_power).publish_state(id(power_consumed));
            
            id(watt).publish_state(id(power_watt));
            
              
switch:
  - platform: gpio
    internal: ${internal_switches}
    name: "${friendly_name} - Fan LOW"
    pin: ${fan_low}
    id: fan_low
    restore_mode: ALWAYS_OFF
    interlock: &interlock [fan_low, fan_high]
      
  - platform: gpio
    internal: ${internal_switches}
    name: "${friendly_name} - Fan HIGH"
    pin: ${fan_high}
    id: fan_high
    restore_mode: ALWAYS_OFF
    interlock: *interlock
      
  - platform: gpio
    internal: ${internal_switches}
    name: "${friendly_name} - Compressor"
    pin: ${compressor}
    id: compressor
    restore_mode: ALWAYS_OFF

globals:
  - id: power_consumed
    type: float
    restore_value: no
    initial_value: '0'
    
  - id: power_watt
    type: float
    restore_value: no
    initial_value: '0'

sensor:
  - platform: homeassistant
    id: ha_temperature
    entity_id: sensor.workroom_sonoff_4ch_temperature_2
    
  - platform: template
    name: "${friendly_name} - Total energy"
    id: total_power
    unit_of_measurement: 'kWh'
    device_class: energy
    state_class: total_increasing
    icon: mdi:home-lightning-bolt-outline
    accuracy_decimals: 3
    lambda: return id(power_consumed);
    filters:
      delta: 0.001
      
  - platform: template
    name: "${friendly_name} - Estimated power consumption"
    id: watt
    unit_of_measurement: 'W'
    state_class: measurement
    device_class: power
    icon: mdi:flash-outline
    accuracy_decimals: 0
    lambda: return id(power_watt);
    filters:
      delta: 1.0
    
climate:
  - platform: thermostat
    id: acthermostat
    name: "${friendly_name} - Thermostat"
    default_mode: "off"
    sensor: ha_temperature
    
    default_target_temperature_high: 23 °C
    
    cool_deadband: 0.05 °C # The minimum temperature differential (temperature above the set point) before engaging cooling
    cool_overrun: 0.05 °C # The minimum temperature differential (cooling beyond the set point) before disengaging cooling
    
    visual:
      min_temperature: 20 °C
      max_temperature: 35 °C
      temperature_step: 0.5 °C

    min_cooling_off_time: 120s
    min_cooling_run_time: 300s

    fan_with_cooling: true # This is useful for forced-air systems where the fan typically runs with cooling.
    
    fan_only_cooling: false
    min_fanning_off_time: 1s
    min_fanning_run_time: 1s
    
    min_idle_time: 1s

    idle_action:
      - switch.turn_off: compressor
    
    off_mode:
      - switch.turn_off: fan_high
      - switch.turn_off: fan_low
      - switch.turn_off: compressor
      
    fan_only_action:
      if:
        condition:
          and:
            - switch.is_off: fan_high
            - switch.is_off: fan_low
        then:
          - switch.turn_on: fan_low
      
    cool_action:
      - switch.turn_on: compressor
